### ISSUE TITLE
user can rate a course multiple times

### ISSUE THREAD

**Issue by dungwoong** [CSC207-UofT/course-project-group-010#104]
eg. rate 10 rate 5 will make the rating 8.75

**Comment by boxspah** [comment]
I think if the same user rates a course twice, it should just overwrite the user's previous rating for that course.

**Comment by dungwoong** [comment]
I changed it in CourseManager.

**Comment by csclover420** [comment]
I think this was resolved, but for some reason Instructors sometimes randomly have authority to rate, and when they can it's multiple times. Probably some local issue on my end but keep in mind.
