### ISSUE TITLE
ratings should be constants

### ISSUE THREAD

**Issue by dungwoong** [CSC207-UofT/course-project-group-010#106]
rating values should be constants, and we should have a factory or something that gets the values to print. We just have "N/A" and stuff scattered all over our program

**Comment by dungwoong** [comment]
i meant to say program names, and yes I made ProgramConstants

**Comment by csclover420** [comment]
wait what exactly should be constant? The rating VALUE (like double/float number) should refer to a constant?

**Comment by dungwoong** [comment]
the program names, like DATA SCIENCE, etc.
