### ISSUE TITLE
RateCommand parsing rating values to int instead of double

### ISSUE THREAD

**Issue by boxspah** [CSC207-UofT/course-project-group-010#123]
In [RateCommand.run](https://github.com/CSC207-UofT/course-project-group-010/blob/6e75d460d87626a94aa4c54594e901fa8b586628/src/main/java/controller/commands/coursecommands/RateCommand.java), the user-provided argument is parsed as `int`, even though ratings are treated as `double` (or in the past, `float`) throughout the program.

This will lead to unexpected behaviour when the user provides a floating-point rating value (e.g. `8.5`); it will be stored as `8`.

**Comment by dungwoong** [comment]
fixed it, also added an exception if the rating couldn't be parsed

**Comment by csclover420** [comment]
the ratings are now from 0-10 instead of 0-1
