### ISSUE TITLE
Misplaced rating value bound check

### ISSUE THREAD

**Issue by boxspah** [CSC207-UofT/course-project-group-010#124]
Currently, whether a user-provided rating value is in-bounds is checked in [CourseManager](https://github.com/CSC207-UofT/course-project-group-010/blob/6e75d460d87626a94aa4c54594e901fa8b586628/src/main/java/usecase/CourseManager.java) (lines 59-61).

This feels like a violation of Clean Architecture principles: why should CourseManager care about how Rating is implemented?

**Suggested solution:**

1. CourseManager calls Rating constructor with parsed user rating value **in a try-except block**.
2. Check in-bounds condition in Rating constructor.
  a. If in-bounds, create Rating object normally.
  b. If out-of-bounds, throw an exception.
3. CourseManager catches the exception if one is thrown and rethrows it up to the command line. Otherwise, proceed normally.

**Comment by dungwoong** [comment]
i fixed it by placing the bound check within Rating's initializer, and adding MAX_VALUE and MIN_VALUE as constants in Rating

**Comment by csclover420** [comment]
MAX_VALUE and MIN_VALUE field can be converted to a local variable. Small issue but keep in mind.

**Comment by boxspah** [comment]
> MAX_VALUE and MIN_VALUE field can be converted to a local variable. Small issue but keep in mind.

I agree with @dungwoong storing `MAX_VALUE` and `MIN_VALUE` as class-level constants. The rating limits should be available to all contained methods at all times because the limits are a kind of invariant. The limits are not just information that is temporarily used at instantiation.

**Comment by csclover420** [comment]
> > MAX_VALUE and MIN_VALUE field can be converted to a local variable. Small issue but keep in mind.
> 
> I agree with @dungwoong storing `MAX_VALUE` and `MIN_VALUE` as class-level constants. The rating limits should be available to all contained methods at all times because the limits are a kind of invariant. The limits are not just information that is temporarily used at instantiation.

yeah I'm just concerned about the javadoc issue, we can't just argue every small little issue IntelliJ finds in our document, so I hope TA let's us explain each issue
