### ISSUE TITLE
Comment commands work incorrectly when logged in as instructor/checking out a course

### ISSUE THREAD

**Issue by noahsub** [CSC207-UofT/course-project-group-010#90]
Program runs into errors when attempting to use comment commands when logged in as an instructor or checking out a course. Currently, only way to use comment commands is to use checkout -c or getcomments.

**Comment by dungwoong** [comment]
I fixed it using the authorization system. I think the authorization system is more about telling what actions are possible, and not what actions are allowed at this point.

**Comment by csclover420** [comment]
the rating authorization bug I mentioned earlier was resolved as a result of this merge, so we're good on that
