### ISSUE TITLE
When a user replies to a comment with an invalid id, the comment is stored as an independent vertex.

### ISSUE THREAD

**Issue by noahsub** [CSC207-UofT/course-project-group-010#94]
When a user replies to a comment with an invalid id, the comment is stored as an independent vertex. This is bad because the new comment that should not exist is now part of the graph but hidden as it has no edges leading to it.

**Comment by fionali90** [comment]
yeah. if the user's invalid, he/she should not be able to get into the review app and leave the comment.

**Comment by csclover420** [comment]
An invalid ID exception was implemented for this right? I thought invalidID exception was for user login.
